export const GET_CURRENCY_LIST_REQUEST = "GET_CURRENCY_LIST_REQUEST";
export const GET_CURRENCY_LIST_SUCCESS = "GET_CURRENCY_LIST_SUCCESS";
export const GET_CURRENCY_LIST_FAILURE = "GET_CURRENCY_LIST_FAILURE";